name: Deploy to Pylex

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          curl -X POST https://deploy.pylex.cloud/api/deploy \
            -H "Content-Type: application/json" \
            -d '{
              "username": "c69p2w",
              "password": "Ww!$nU1P4#Sslp*z4^%q3&lf5&z#VpTX",
              "appName": "deploy",
              "appPassword": "Samadgod269",
              "repo": "https://github.com/samadgod569/Index.html.git",
              "language": "nodejs",
              "startFile": "index.js",
              "packages": []
            }'
